# Generated by Django 4.1.2 on 2023-06-07 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact", name="slno", field=models.TextField(max_length=250),
        ),
    ]
