# Generated by Django 4.1.2 on 2023-06-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crudapp", "0002_alter_contact_slno"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="description",
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name="contact", name="slno", field=models.CharField(max_length=250),
        ),
    ]
